# docker-compose.yml - VERSION FINALE

services:
  zordb:
    image: postgres:15-alpine
    container_name: zordb-zorzap
    restart: always
    environment:
      # Assurez-vous que ces valeurs sont correctes pour votre projet
      POSTGRES_USER: zoruser
      POSTGRES_PASSWORD: zorpassword
      POSTGRES_DB: zordb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./iac/postgres:/docker-entrypoint-initdb.d
    networks:
      - zorzap-net

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard-zorzap
    restart: always
    ports:
      - "8888:80"
    environment:
      - DATABASE_URL=postgres://zoruser:zorpassword@zordb:5432/zordb
    depends_on:
      - zordb
    volumes:
      - kanboard-data:/var/www/app/data
      - kanboard-plugins:/var/www/app/plugins
    networks:
      - zorzap-net

  jenkins:
    # On donne un nom à l'image que l'on construit
    image: zorzap-jenkins:custom
    # On indique où trouver le Dockerfile
    build:
      context: ./iac/jenkins
    container_name: jenkins-zorzap
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Le nom du volume ici doit correspondre à la déclaration ci-dessous
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - zorzap-net

# --- Déclaration des Volumes et du Réseau ---
# Cette section doit être tout en bas et sans indentation

volumes:
  postgres-data:
  kanboard-data:
  kanboard-plugins:
  jenkins-data:

networks:
  zorzap-net:
    driver: bridge
    